const data3 = [
  { id: 1, img: "https://i.ibb.co/R0B7tTB/row-1-column-1.jpg" },
  { id: 25, img: "https://i.ibb.co/56HcwCQ/row-5-column-5.jpg" },
  { id: 4, img: "https://i.ibb.co/wWs3Z1D/row-1-column-4.jpg" },
  { id: 9, img: "https://i.ibb.co/qsw8D0P/row-2-column-4.jpg" },
  { id: 7, img: "https://i.ibb.co/jkSRcVY/row-2-column-2.jpg" },
  { id: 2, img: "https://i.ibb.co/DDRDPnF/row-1-column-2.jpg" },
  { id: 24, img: "https://i.ibb.co/0hpgwPZ/row-5-column-4.jpg" },
  { id: 8, img: "https://i.ibb.co/RYt9YBs/row-2-column-3.jpg" },
  { id: 3, img: "https://i.ibb.co/vwG2dmh/row-1-column-3.jpg" },
  { id: 14, img: "https://i.ibb.co/4j1Zvrh/row-3-column-4.jpg" },
  { id: 10, img: "https://i.ibb.co/TgL2YcP/row-2-column-5.jpg" },
  { id: 12, img: "https://i.ibb.co/cy7MhTq/row-3-column-2.jpg" },
  { id: 5, img: "https://i.ibb.co/NtvMzWB/row-1-column-5.jpg" },
  { id: 15, img: "https://i.ibb.co/TP0WcGM/row-3-column-5.jpg" },
  { id: 22, img: "https://i.ibb.co/T8TjY8X/row-5-column-2.jpg" },
  { id: 16, img: "https://i.ibb.co/JCy3YgD/row-4-column-1.jpg" },
  { id: 17, img: "https://i.ibb.co/dKqshzj/row-4-column-2.jpg" },
  { id: 19, img: "https://i.ibb.co/xzfJbCn/row-4-column-4.jpg" },
  { id: 13, img: "https://i.ibb.co/vJJ3MHG/row-3-column-3.jpg" },
  { id: 6, img: "https://i.ibb.co/FYvS9ym/row-2-column-1.jpg" },
  { id: 20, img: "https://i.ibb.co/dGz8GXy/row-4-column-5.jpg" },
  { id: 11, img: "https://i.ibb.co/xsr8Wsk/row-3-column-1.jpg" },
  { id: 21, img: "https://i.ibb.co/5vVyd4t/row-5-column-1.jpg" },
  { id: 18, img: "https://i.ibb.co/9sLnfjd/row-4-column-3.jpg" },
  { id: 23, img: "https://i.ibb.co/DVkS44W/row-5-column-3.jpg" },
];
export default data3;