const data2 = [
  { id: 2, img: "https://i.ibb.co/q1hf5yn/row-1-column-2.jpg" },
  { id: 3, img: "https://i.ibb.co/T8qfWRQ/row-1-column-3.jpg" },
  { id: 6, img: "https://i.ibb.co/42s9X1B/row-2-column-1.jpg" },
  { id: 4, img: "https://i.ibb.co/SwpPhp3/row-1-column-4.jpg" },
  { id: 1, img: "https://i.ibb.co/hHq92wY/row-1-column-1.jpg" },
  { id: 7, img: "https://i.ibb.co/QnnFY3Y/row-2-column-2.jpg" },
  { id: 8, img: "https://i.ibb.co/bd222wq/row-2-column-3.jpg" },
  { id: 10, img: "https://i.ibb.co/5kMfdvm/row-2-column-5.jpg" },
  { id: 12, img: "https://i.ibb.co/fCnv80M/row-3-column-2.jpg" },
  { id: 9, img: "https://i.ibb.co/vBczPgG/row-2-column-4.jpg" },
  { id: 11, img: "https://i.ibb.co/4KgbpQ9/row-3-column-1.jpg" },
  { id: 17, img: "https://i.ibb.co/qnWPmT5/row-4-column-2.jpg" },
  { id: 14, img: "https://i.ibb.co/44V2Pj7/row-3-column-4.jpg" },
  { id: 13, img: "https://i.ibb.co/dBYYjFW/row-3-column-3.jpg" },
  { id: 15, img: "https://i.ibb.co/b7wYnMc/row-3-column-5.jpg" },
  { id: 5, img: "https://i.ibb.co/tBKnzG1/row-1-column-5.jpg" },
  { id: 18, img: "https://i.ibb.co/cby0zYn/row-4-column-3.jpg" },
  { id: 16, img: "https://i.ibb.co/grWHtRb/row-4-column-1.jpg" },
  { id: 25, img: "https://i.ibb.co/2383PxK/row-5-column-5.jpg" },
  { id: 19, img: "https://i.ibb.co/DKzGHZQ/row-4-column-4.jpg" },
  { id: 22, img: "https://i.ibb.co/qM7CPvx/row-5-column-2.jpg" },
  { id: 21, img: "https://i.ibb.co/wQzw5JZ/row-5-column-1.jpg" },
  { id: 23, img: "https://i.ibb.co/v4ZrsCv/row-5-column-3.jpg" },
  { id: 24, img: "https://i.ibb.co/Q9Dnn02/row-5-column-4.jpg" },
  { id: 20, img: "https://i.ibb.co/cvGzGwb/row-4-column-5.jpg" },
];

export default data2;
