const data1 = [
  { id: 5, img: "https://i.ibb.co/8bG29r4/row-1-column-5.jpg" },
  { id: 3, img: "https://i.ibb.co/Z6m3WDq/row-1-column-3.jpg" },
  { id: 8, img: "https://i.ibb.co/h9KZKGV/row-2-column-3.jpg" },
  { id: 23, img: "https://i.ibb.co/dJLjch7/row-5-column-3.jpg" },
  { id: 9, img: "https://i.ibb.co/gRRMVHW/row-2-column-4.jpg" },
  { id: 6, img: "https://i.ibb.co/yX5bPZ2/row-2-column-1.jpg" },
  { id: 7, img: "https://i.ibb.co/dPX6FHD/row-2-column-2.jpg" },
  { id: 4, img: "https://i.ibb.co/0FT6sCd/row-1-column-4.jpg" },
  { id: 2, img: "https://i.ibb.co/6m34jRb/row-1-column-2.jpg" },
  { id: 21, img: "https://i.ibb.co/k6nY6Gt/row-5-column-1.jpg" },
  { id: 10, img: "https://i.ibb.co/74WrGR3/row-2-column-5.jpg" },
  { id: 11, img: "https://i.ibb.co/0qsBwRw/row-3-column-1.jpg" },
  { id: 17, img: "https://i.ibb.co/v3ZNbLR/row-4-column-2.jpg" },
  { id: 15, img: "https://i.ibb.co/p3TdwXP/row-3-column-5.jpg" },
  { id: 13, img: "https://i.ibb.co/X8SVB5Z/row-3-column-3.jpg" },
  { id: 19, img: "https://i.ibb.co/P5LSyDS/row-4-column-4.jpg" },
  { id: 1, img: "https://i.ibb.co/zmYvjxv/row-1-column-1.jpg" },
  { id: 12, img: "https://i.ibb.co/bdgrD1B/row-3-column-2.jpg" },
  { id: 18, img: "https://i.ibb.co/R7mhgz9/row-4-column-3.jpg" },
  { id: 24, img: "https://i.ibb.co/2Yx7nPc/row-5-column-4.jpg" },
  { id: 16, img: "https://i.ibb.co/ZMJpBFB/row-4-column-1.jpg" },
  { id: 22, img: "https://i.ibb.co/n1DC2V6/row-5-column-2.jpg" },
  { id: 14, img: "https://i.ibb.co/dJTY5NT/row-3-column-4.jpg" },
  { id: 25, img: "https://i.ibb.co/X20W7D8/row-5-column-5.jpg" },
  { id: 20, img: "https://i.ibb.co/yW0XWxM/row-4-column-5.jpg" },
]

export default data1